"""add raw instance points

Revision ID: 159ffc9db439
Revises: 1bb81b70e991
Create Date: 2026-09-08 02:16:59.890355+00:00

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '159ffc9db439'
down_revision: str | None = '1bb81b70e991'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('box_fittings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('points_depth_raw_ego', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('points_lidar_raw_ego', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('num_points_depth_kept', sa.Integer(), server_default=sa.text('0'), nullable=False))
        batch_op.add_column(sa.Column('num_points_lidar_kept', sa.Integer(), server_default=sa.text('0'), nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('box_fittings', schema=None) as batch_op:
        batch_op.drop_column('num_points_lidar_kept')
        batch_op.drop_column('num_points_depth_kept')
        batch_op.drop_column('points_lidar_raw_ego')
        batch_op.drop_column('points_depth_raw_ego')

    # ### end Alembic commands ###
