"""init schema

Revision ID: 2137e2545219
Revises: 
Create Date: 2026-08-30 14:08:39.004692+00:00

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2137e2545219'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('datasets',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('dataset_type', sa.String(), nullable=False),
    sa.Column('version', sa.String(), nullable=True),
    sa.Column('dataroot', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_datasets')),
    sa.UniqueConstraint('name', name=op.f('uq_datasets_name'))
    )
    op.create_table('attributes',
    sa.Column('token', sa.String(), nullable=False),
    sa.Column('dataset_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['dataset_id'], ['datasets.id'], name=op.f('fk_attributes_dataset_id_datasets'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('token', name=op.f('pk_attributes'))
    )
    with op.batch_alter_table('attributes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_attributes_dataset_id'), ['dataset_id'], unique=False)

    op.create_table('categories',
    sa.Column('token', sa.String(), nullable=False),
    sa.Column('dataset_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['dataset_id'], ['datasets.id'], name=op.f('fk_categories_dataset_id_datasets'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('token', name=op.f('pk_categories'))
    )
    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_categories_dataset_id'), ['dataset_id'], unique=False)
        batch_op.create_index('ix_categories_dataset_name', ['dataset_id', 'name'], unique=True)

    op.create_table('ego_poses',
    sa.Column('token', sa.String(), nullable=False),
    sa.Column('dataset_id', sa.String(), nullable=False),
    sa.Column('timestamp', sa.BigInteger(), nullable=False),
    sa.Column('translation', sa.JSON(), nullable=False),
    sa.Column('rotation', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['dataset_id'], ['datasets.id'], name=op.f('fk_ego_poses_dataset_id_datasets'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('token', name=op.f('pk_ego_poses'))
    )
    with op.batch_alter_table('ego_poses', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ego_poses_dataset_id'), ['dataset_id'], unique=False)

    op.create_table('logs',
    sa.Column('token', sa.String(), nullable=False),
    sa.Column('dataset_id', sa.String(), nullable=False),
    sa.Column('source_token', sa.String(), nullable=True),
    sa.Column('logfile', sa.String(), nullable=False),
    sa.Column('vehicle', sa.String(), nullable=False),
    sa.Column('date_captured', sa.String(), nullable=False),
    sa.Column('location', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['dataset_id'], ['datasets.id'], name=op.f('fk_logs_dataset_id_datasets'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('token', name=op.f('pk_logs'))
    )
    with op.batch_alter_table('logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_logs_dataset_id'), ['dataset_id'], unique=False)
        batch_op.create_index('ix_logs_dataset_location', ['dataset_id', 'location'], unique=False)

    op.create_table('map_meta',
    sa.Column('token', sa.String(), nullable=False),
    sa.Column('dataset_id', sa.String(), nullable=False),
    sa.Column('location', sa.String(), nullable=False),
    sa.Column('version', sa.String(), nullable=False),
    sa.Column('canvas_edge', sa.JSON(), nullable=False),
    sa.Column('basemap_path', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['dataset_id'], ['datasets.id'], name=op.f('fk_map_meta_dataset_id_datasets'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('token', name=op.f('pk_map_meta'))
    )
    with op.batch_alter_table('map_meta', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_map_meta_dataset_id'), ['dataset_id'], unique=False)
        batch_op.create_index('ix_map_meta_dataset_location', ['dataset_id', 'location'], unique=False)

    op.create_table('sensors',
    sa.Column('token', sa.String(), nullable=False),
    sa.Column('dataset_id', sa.String(), nullable=False),
    sa.Column('channel', sa.String(), nullable=False),
    sa.Column('modality', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['dataset_id'], ['datasets.id'], name=op.f('fk_sensors_dataset_id_datasets'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('token', name=op.f('pk_sensors'))
    )
    with op.batch_alter_table('sensors', schema=None) as batch_op:
        batch_op.create_index('ix_sensors_dataset_channel', ['dataset_id', 'channel'], unique=False)
        batch_op.create_index(batch_op.f('ix_sensors_dataset_id'), ['dataset_id'], unique=False)

    op.create_table('visibilities',
    sa.Column('token', sa.String(), nullable=False),
    sa.Column('dataset_id', sa.String(), nullable=False),
    sa.Column('level', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['dataset_id'], ['datasets.id'], name=op.f('fk_visibilities_dataset_id_datasets'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('token', name=op.f('pk_visibilities'))
    )
    with op.batch_alter_table('visibilities', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_visibilities_dataset_id'), ['dataset_id'], unique=False)

    op.create_table('calibrated_sensors',
    sa.Column('token', sa.String(), nullable=False),
    sa.Column('dataset_id', sa.String(), nullable=False),
    sa.Column('sensor_token', sa.String(), nullable=False),
    sa.Column('translation', sa.JSON(), nullable=False),
    sa.Column('rotation', sa.JSON(), nullable=False),
    sa.Column('camera_intrinsic', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['dataset_id'], ['datasets.id'], name=op.f('fk_calibrated_sensors_dataset_id_datasets'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sensor_token'], ['sensors.token'], name=op.f('fk_calibrated_sensors_sensor_token_sensors'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('token', name=op.f('pk_calibrated_sensors'))
    )
    with op.batch_alter_table('calibrated_sensors', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_calibrated_sensors_dataset_id'), ['dataset_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_calibrated_sensors_sensor_token'), ['sensor_token'], unique=False)

    op.create_table('instances',
    sa.Column('token', sa.String(), nullable=False),
    sa.Column('dataset_id', sa.String(), nullable=False),
    sa.Column('category_token', sa.String(), nullable=False),
    sa.Column('nbr_annotations', sa.Integer(), nullable=False),
    sa.Column('first_annotation_token', sa.String(), nullable=True),
    sa.Column('last_annotation_token', sa.String(), nullable=True),
    sa.Column('source', sa.String(), server_default=sa.text("'imported'"), nullable=False),
    sa.ForeignKeyConstraint(['category_token'], ['categories.token'], name=op.f('fk_instances_category_token_categories'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['dataset_id'], ['datasets.id'], name=op.f('fk_instances_dataset_id_datasets'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('token', name=op.f('pk_instances'))
    )
    with op.batch_alter_table('instances', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_instances_category_token'), ['category_token'], unique=False)
        batch_op.create_index(batch_op.f('ix_instances_dataset_id'), ['dataset_id'], unique=False)

    op.create_table('scenes',
    sa.Column('token', sa.String(), nullable=False),
    sa.Column('dataset_id', sa.String(), nullable=False),
    sa.Column('log_token', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('nbr_samples', sa.Integer(), nullable=False),
    sa.Column('first_sample_token', sa.String(), nullable=False),
    sa.Column('last_sample_token', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['dataset_id'], ['datasets.id'], name=op.f('fk_scenes_dataset_id_datasets'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['log_token'], ['logs.token'], name=op.f('fk_scenes_log_token_logs'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('token', name=op.f('pk_scenes'))
    )
    with op.batch_alter_table('scenes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_scenes_dataset_id'), ['dataset_id'], unique=False)
        batch_op.create_index('ix_scenes_dataset_log_token', ['dataset_id', 'log_token'], unique=False)
        batch_op.create_index(batch_op.f('ix_scenes_log_token'), ['log_token'], unique=False)

    op.create_table('detection_2d_params',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('dataset_id', sa.String(), nullable=False),
    sa.Column('scene_token', sa.String(), nullable=False),
    sa.Column('model_name', sa.String(), nullable=False),
    sa.Column('sample_interval', sa.Integer(), nullable=False),
    sa.Column('nusc_category_to_label', sa.JSON(), nullable=False),
    sa.Column('label_to_nusc_category', sa.JSON(), nullable=False),
    sa.Column('label_to_category_group', sa.JSON(), nullable=False),
    sa.Column('score_threshold', sa.JSON(), nullable=False),
    sa.Column('nms_same_class_ious', sa.JSON(), nullable=False),
    sa.Column('nms_cross_class_ious', sa.JSON(), nullable=False),
    sa.Column('num_inferences', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('inference_time', sa.Float(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['dataset_id'], ['datasets.id'], name=op.f('fk_detection_2d_params_dataset_id_datasets'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['scene_token'], ['scenes.token'], name=op.f('fk_detection_2d_params_scene_token_scenes'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_detection_2d_params'))
    )
    with op.batch_alter_table('detection_2d_params', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_detection_2d_params_dataset_id'), ['dataset_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_detection_2d_params_scene_token'), ['scene_token'], unique=False)

    op.create_table('samples',
    sa.Column('token', sa.String(), nullable=False),
    sa.Column('dataset_id', sa.String(), nullable=False),
    sa.Column('scene_token', sa.String(), nullable=False),
    sa.Column('timestamp', sa.BigInteger(), nullable=False),
    sa.Column('prev', sa.String(), nullable=True),
    sa.Column('next', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['dataset_id'], ['datasets.id'], name=op.f('fk_samples_dataset_id_datasets'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['next'], ['samples.token'], name=op.f('fk_samples_next_samples'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['prev'], ['samples.token'], name=op.f('fk_samples_prev_samples'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['scene_token'], ['scenes.token'], name=op.f('fk_samples_scene_token_scenes'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('token', name=op.f('pk_samples'))
    )
    with op.batch_alter_table('samples', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_samples_dataset_id'), ['dataset_id'], unique=False)
        batch_op.create_index('ix_samples_dataset_scene_token', ['dataset_id', 'scene_token'], unique=False)
        batch_op.create_index(batch_op.f('ix_samples_next'), ['next'], unique=False)
        batch_op.create_index(batch_op.f('ix_samples_prev'), ['prev'], unique=False)
        batch_op.create_index('ix_samples_scene_timestamp', ['scene_token', 'timestamp'], unique=False)
        batch_op.create_index(batch_op.f('ix_samples_scene_token'), ['scene_token'], unique=False)

    op.create_table('instance_tracking_2d_params',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('dataset_id', sa.String(), nullable=False),
    sa.Column('scene_token', sa.String(), nullable=False),
    sa.Column('detection_2d_params_id', sa.String(), nullable=False),
    sa.Column('model_name', sa.String(), nullable=False),
    sa.Column('sample_interval', sa.Integer(), nullable=False),
    sa.Column('mask_score_threshold', sa.Float(), nullable=False),
    sa.Column('new_track_iou_threshold', sa.Float(), nullable=False),
    sa.Column('max_lost_frames', sa.Integer(), nullable=False),
    sa.Column('num_inferences', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('num_tracks', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('inference_time', sa.Float(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['dataset_id'], ['datasets.id'], name=op.f('fk_instance_tracking_2d_params_dataset_id_datasets'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['detection_2d_params_id'], ['detection_2d_params.id'], name=op.f('fk_instance_tracking_2d_params_detection_2d_params_id_detection_2d_params'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['scene_token'], ['scenes.token'], name=op.f('fk_instance_tracking_2d_params_scene_token_scenes'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_instance_tracking_2d_params'))
    )
    with op.batch_alter_table('instance_tracking_2d_params', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_instance_tracking_2d_params_dataset_id'), ['dataset_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_instance_tracking_2d_params_detection_2d_params_id'), ['detection_2d_params_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_instance_tracking_2d_params_scene_token'), ['scene_token'], unique=False)

    op.create_table('sample_data',
    sa.Column('token', sa.String(), nullable=False),
    sa.Column('dataset_id', sa.String(), nullable=False),
    sa.Column('sample_token', sa.String(), nullable=False),
    sa.Column('calibrated_sensor_token', sa.String(), nullable=False),
    sa.Column('ego_pose_token', sa.String(), nullable=False),
    sa.Column('filename', sa.String(), nullable=False),
    sa.Column('fileformat', sa.String(), nullable=False),
    sa.Column('timestamp', sa.BigInteger(), nullable=False),
    sa.Column('is_key_frame', sa.Boolean(), nullable=False),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('prev', sa.String(), nullable=True),
    sa.Column('next', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['calibrated_sensor_token'], ['calibrated_sensors.token'], name=op.f('fk_sample_data_calibrated_sensor_token_calibrated_sensors'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['dataset_id'], ['datasets.id'], name=op.f('fk_sample_data_dataset_id_datasets'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['ego_pose_token'], ['ego_poses.token'], name=op.f('fk_sample_data_ego_pose_token_ego_poses'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['next'], ['sample_data.token'], name=op.f('fk_sample_data_next_sample_data'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['prev'], ['sample_data.token'], name=op.f('fk_sample_data_prev_sample_data'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['sample_token'], ['samples.token'], name=op.f('fk_sample_data_sample_token_samples'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('token', name=op.f('pk_sample_data'))
    )
    with op.batch_alter_table('sample_data', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sample_data_calibrated_sensor_token'), ['calibrated_sensor_token'], unique=False)
        batch_op.create_index(batch_op.f('ix_sample_data_dataset_id'), ['dataset_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_sample_data_ego_pose_token'), ['ego_pose_token'], unique=False)
        batch_op.create_index(batch_op.f('ix_sample_data_next'), ['next'], unique=False)
        batch_op.create_index(batch_op.f('ix_sample_data_prev'), ['prev'], unique=False)
        batch_op.create_index('ix_sample_data_sample_key_frame', ['sample_token', 'is_key_frame'], unique=False)

    op.create_table('depth_estimation_params',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('dataset_id', sa.String(), nullable=False),
    sa.Column('scene_token', sa.String(), nullable=False),
    sa.Column('instance_tracking_2d_params_id', sa.String(), nullable=False),
    sa.Column('model_name', sa.String(), nullable=False),
    sa.Column('sample_interval', sa.Integer(), nullable=False),
    sa.Column('depth_alignment_method', sa.String(), nullable=False),
    sa.Column('point_fusion_mode', sa.String(), nullable=False),
    sa.Column('box_fitting_method', sa.String(), nullable=False),
    sa.Column('min_points_per_box', sa.Integer(), nullable=False),
    sa.Column('outlier_percentile', sa.Float(), nullable=False),
    sa.Column('max_depth', sa.Float(), nullable=False),
    sa.Column('extra_options', sa.JSON(), nullable=True),
    sa.Column('num_inferences', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('num_boxes', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('inference_time', sa.Float(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['dataset_id'], ['datasets.id'], name=op.f('fk_depth_estimation_params_dataset_id_datasets'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['instance_tracking_2d_params_id'], ['instance_tracking_2d_params.id'], name=op.f('fk_depth_estimation_params_instance_tracking_2d_params_id_instance_tracking_2d_params'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['scene_token'], ['scenes.token'], name=op.f('fk_depth_estimation_params_scene_token_scenes'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_depth_estimation_params'))
    )
    with op.batch_alter_table('depth_estimation_params', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_depth_estimation_params_dataset_id'), ['dataset_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_depth_estimation_params_instance_tracking_2d_params_id'), ['instance_tracking_2d_params_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_depth_estimation_params_scene_token'), ['scene_token'], unique=False)

    op.create_table('detection_2ds',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('dataset_id', sa.String(), nullable=False),
    sa.Column('sample_data_token', sa.String(), nullable=False),
    sa.Column('detection_2d_params_id', sa.String(), nullable=False),
    sa.Column('xmin', sa.Integer(), nullable=False),
    sa.Column('ymin', sa.Integer(), nullable=False),
    sa.Column('xmax', sa.Integer(), nullable=False),
    sa.Column('ymax', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(), nullable=False),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('manually_modified', sa.Boolean(), server_default=sa.text('0'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['dataset_id'], ['datasets.id'], name=op.f('fk_detection_2ds_dataset_id_datasets'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['detection_2d_params_id'], ['detection_2d_params.id'], name=op.f('fk_detection_2ds_detection_2d_params_id_detection_2d_params'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sample_data_token'], ['sample_data.token'], name=op.f('fk_detection_2ds_sample_data_token_sample_data'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_detection_2ds'))
    )
    with op.batch_alter_table('detection_2ds', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_detection_2ds_dataset_id'), ['dataset_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_detection_2ds_detection_2d_params_id'), ['detection_2d_params_id'], unique=False)
        batch_op.create_index('ix_detection_2ds_params_sample_data', ['detection_2d_params_id', 'sample_data_token'], unique=False)
        batch_op.create_index(batch_op.f('ix_detection_2ds_sample_data_token'), ['sample_data_token'], unique=False)

    op.create_table('depth_estimations',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('dataset_id', sa.String(), nullable=False),
    sa.Column('sample_data_token', sa.String(), nullable=False),
    sa.Column('depth_estimation_params_id', sa.String(), nullable=False),
    sa.Column('depth_path', sa.String(), nullable=False),
    sa.Column('scale', sa.Float(), nullable=True),
    sa.Column('shift', sa.Float(), nullable=True),
    sa.Column('min_depth', sa.Float(), nullable=True),
    sa.Column('max_depth', sa.Float(), nullable=True),
    sa.Column('num_points', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['dataset_id'], ['datasets.id'], name=op.f('fk_depth_estimations_dataset_id_datasets'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['depth_estimation_params_id'], ['depth_estimation_params.id'], name=op.f('fk_depth_estimations_depth_estimation_params_id_depth_estimation_params'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sample_data_token'], ['sample_data.token'], name=op.f('fk_depth_estimations_sample_data_token_sample_data'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_depth_estimations'))
    )
    with op.batch_alter_table('depth_estimations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_depth_estimations_dataset_id'), ['dataset_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_depth_estimations_depth_estimation_params_id'), ['depth_estimation_params_id'], unique=False)
        batch_op.create_index('ix_depth_estimations_params_sample_data', ['depth_estimation_params_id', 'sample_data_token'], unique=False)
        batch_op.create_index(batch_op.f('ix_depth_estimations_sample_data_token'), ['sample_data_token'], unique=False)

    op.create_table('instance_tracking_2ds',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('dataset_id', sa.String(), nullable=False),
    sa.Column('sample_data_token', sa.String(), nullable=False),
    sa.Column('instance_tracking_2d_params_id', sa.String(), nullable=False),
    sa.Column('detection_2d_id', sa.String(), nullable=True),
    sa.Column('track_id', sa.String(), nullable=False),
    sa.Column('label', sa.String(), nullable=False),
    sa.Column('mask_rle', sa.JSON(), nullable=False),
    sa.Column('mask_area', sa.Integer(), nullable=False),
    sa.Column('xmin', sa.Integer(), nullable=False),
    sa.Column('ymin', sa.Integer(), nullable=False),
    sa.Column('xmax', sa.Integer(), nullable=False),
    sa.Column('ymax', sa.Integer(), nullable=False),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('instance_token', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('manually_modified', sa.Boolean(), server_default=sa.text('0'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['dataset_id'], ['datasets.id'], name=op.f('fk_instance_tracking_2ds_dataset_id_datasets'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['detection_2d_id'], ['detection_2ds.id'], name=op.f('fk_instance_tracking_2ds_detection_2d_id_detection_2ds'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['instance_token'], ['instances.token'], name=op.f('fk_instance_tracking_2ds_instance_token_instances'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['instance_tracking_2d_params_id'], ['instance_tracking_2d_params.id'], name=op.f('fk_instance_tracking_2ds_instance_tracking_2d_params_id_instance_tracking_2d_params'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sample_data_token'], ['sample_data.token'], name=op.f('fk_instance_tracking_2ds_sample_data_token_sample_data'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_instance_tracking_2ds'))
    )
    with op.batch_alter_table('instance_tracking_2ds', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_instance_tracking_2ds_dataset_id'), ['dataset_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_instance_tracking_2ds_detection_2d_id'), ['detection_2d_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_instance_tracking_2ds_instance_token'), ['instance_token'], unique=False)
        batch_op.create_index(batch_op.f('ix_instance_tracking_2ds_instance_tracking_2d_params_id'), ['instance_tracking_2d_params_id'], unique=False)
        batch_op.create_index('ix_instance_tracking_2ds_params_sample_data', ['instance_tracking_2d_params_id', 'sample_data_token'], unique=False)
        batch_op.create_index('ix_instance_tracking_2ds_params_track', ['instance_tracking_2d_params_id', 'track_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_instance_tracking_2ds_sample_data_token'), ['sample_data_token'], unique=False)

    op.create_table('sample_annotations',
    sa.Column('token', sa.String(), nullable=False),
    sa.Column('dataset_id', sa.String(), nullable=False),
    sa.Column('sample_token', sa.String(), nullable=False),
    sa.Column('instance_token', sa.String(), nullable=False),
    sa.Column('translation', sa.JSON(), nullable=False),
    sa.Column('rotation', sa.JSON(), nullable=False),
    sa.Column('size', sa.JSON(), nullable=False),
    sa.Column('prev', sa.String(), nullable=True),
    sa.Column('next', sa.String(), nullable=True),
    sa.Column('num_lidar_pts', sa.Integer(), nullable=False),
    sa.Column('num_radar_pts', sa.Integer(), nullable=False),
    sa.Column('visibility_token', sa.String(), nullable=True),
    sa.Column('source', sa.String(), server_default=sa.text("'imported'"), nullable=False),
    sa.Column('depth_estimation_params_id', sa.String(), nullable=True),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('manually_modified', sa.Boolean(), server_default=sa.text('0'), nullable=False),
    sa.ForeignKeyConstraint(['dataset_id'], ['datasets.id'], name=op.f('fk_sample_annotations_dataset_id_datasets'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['depth_estimation_params_id'], ['depth_estimation_params.id'], name=op.f('fk_sample_annotations_depth_estimation_params_id_depth_estimation_params'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['instance_token'], ['instances.token'], name=op.f('fk_sample_annotations_instance_token_instances'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['next'], ['sample_annotations.token'], name=op.f('fk_sample_annotations_next_sample_annotations'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['prev'], ['sample_annotations.token'], name=op.f('fk_sample_annotations_prev_sample_annotations'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['sample_token'], ['samples.token'], name=op.f('fk_sample_annotations_sample_token_samples'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['visibility_token'], ['visibilities.token'], name=op.f('fk_sample_annotations_visibility_token_visibilities'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('token', name=op.f('pk_sample_annotations'))
    )
    with op.batch_alter_table('sample_annotations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sample_annotations_dataset_id'), ['dataset_id'], unique=False)
        batch_op.create_index('ix_sample_annotations_dataset_sample_token', ['dataset_id', 'sample_token'], unique=False)
        batch_op.create_index(batch_op.f('ix_sample_annotations_depth_estimation_params_id'), ['depth_estimation_params_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_sample_annotations_instance_token'), ['instance_token'], unique=False)
        batch_op.create_index(batch_op.f('ix_sample_annotations_next'), ['next'], unique=False)
        batch_op.create_index(batch_op.f('ix_sample_annotations_prev'), ['prev'], unique=False)
        batch_op.create_index('ix_sample_annotations_sample_source', ['sample_token', 'source'], unique=False)
        batch_op.create_index(batch_op.f('ix_sample_annotations_sample_token'), ['sample_token'], unique=False)
        batch_op.create_index(batch_op.f('ix_sample_annotations_visibility_token'), ['visibility_token'], unique=False)

    op.create_table('annotation_attributes',
    sa.Column('annotation_token', sa.String(), nullable=False),
    sa.Column('attribute_token', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['annotation_token'], ['sample_annotations.token'], name=op.f('fk_annotation_attributes_annotation_token_sample_annotations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['attribute_token'], ['attributes.token'], name=op.f('fk_annotation_attributes_attribute_token_attributes'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('annotation_token', 'attribute_token', name=op.f('pk_annotation_attributes'))
    )
    with op.batch_alter_table('annotation_attributes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_annotation_attributes_attribute_token'), ['attribute_token'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('annotation_attributes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_annotation_attributes_attribute_token'))

    op.drop_table('annotation_attributes')
    with op.batch_alter_table('sample_annotations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sample_annotations_visibility_token'))
        batch_op.drop_index(batch_op.f('ix_sample_annotations_sample_token'))
        batch_op.drop_index('ix_sample_annotations_sample_source')
        batch_op.drop_index(batch_op.f('ix_sample_annotations_prev'))
        batch_op.drop_index(batch_op.f('ix_sample_annotations_next'))
        batch_op.drop_index(batch_op.f('ix_sample_annotations_instance_token'))
        batch_op.drop_index(batch_op.f('ix_sample_annotations_depth_estimation_params_id'))
        batch_op.drop_index('ix_sample_annotations_dataset_sample_token')
        batch_op.drop_index(batch_op.f('ix_sample_annotations_dataset_id'))

    op.drop_table('sample_annotations')
    with op.batch_alter_table('instance_tracking_2ds', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_instance_tracking_2ds_sample_data_token'))
        batch_op.drop_index('ix_instance_tracking_2ds_params_track')
        batch_op.drop_index('ix_instance_tracking_2ds_params_sample_data')
        batch_op.drop_index(batch_op.f('ix_instance_tracking_2ds_instance_tracking_2d_params_id'))
        batch_op.drop_index(batch_op.f('ix_instance_tracking_2ds_instance_token'))
        batch_op.drop_index(batch_op.f('ix_instance_tracking_2ds_detection_2d_id'))
        batch_op.drop_index(batch_op.f('ix_instance_tracking_2ds_dataset_id'))

    op.drop_table('instance_tracking_2ds')
    with op.batch_alter_table('depth_estimations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_depth_estimations_sample_data_token'))
        batch_op.drop_index('ix_depth_estimations_params_sample_data')
        batch_op.drop_index(batch_op.f('ix_depth_estimations_depth_estimation_params_id'))
        batch_op.drop_index(batch_op.f('ix_depth_estimations_dataset_id'))

    op.drop_table('depth_estimations')
    with op.batch_alter_table('detection_2ds', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_detection_2ds_sample_data_token'))
        batch_op.drop_index('ix_detection_2ds_params_sample_data')
        batch_op.drop_index(batch_op.f('ix_detection_2ds_detection_2d_params_id'))
        batch_op.drop_index(batch_op.f('ix_detection_2ds_dataset_id'))

    op.drop_table('detection_2ds')
    with op.batch_alter_table('depth_estimation_params', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_depth_estimation_params_scene_token'))
        batch_op.drop_index(batch_op.f('ix_depth_estimation_params_instance_tracking_2d_params_id'))
        batch_op.drop_index(batch_op.f('ix_depth_estimation_params_dataset_id'))

    op.drop_table('depth_estimation_params')
    with op.batch_alter_table('sample_data', schema=None) as batch_op:
        batch_op.drop_index('ix_sample_data_sample_key_frame')
        batch_op.drop_index(batch_op.f('ix_sample_data_prev'))
        batch_op.drop_index(batch_op.f('ix_sample_data_next'))
        batch_op.drop_index(batch_op.f('ix_sample_data_ego_pose_token'))
        batch_op.drop_index(batch_op.f('ix_sample_data_dataset_id'))
        batch_op.drop_index(batch_op.f('ix_sample_data_calibrated_sensor_token'))

    op.drop_table('sample_data')
    with op.batch_alter_table('instance_tracking_2d_params', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_instance_tracking_2d_params_scene_token'))
        batch_op.drop_index(batch_op.f('ix_instance_tracking_2d_params_detection_2d_params_id'))
        batch_op.drop_index(batch_op.f('ix_instance_tracking_2d_params_dataset_id'))

    op.drop_table('instance_tracking_2d_params')
    with op.batch_alter_table('samples', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_samples_scene_token'))
        batch_op.drop_index('ix_samples_scene_timestamp')
        batch_op.drop_index(batch_op.f('ix_samples_prev'))
        batch_op.drop_index(batch_op.f('ix_samples_next'))
        batch_op.drop_index('ix_samples_dataset_scene_token')
        batch_op.drop_index(batch_op.f('ix_samples_dataset_id'))

    op.drop_table('samples')
    with op.batch_alter_table('detection_2d_params', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_detection_2d_params_scene_token'))
        batch_op.drop_index(batch_op.f('ix_detection_2d_params_dataset_id'))

    op.drop_table('detection_2d_params')
    with op.batch_alter_table('scenes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_scenes_log_token'))
        batch_op.drop_index('ix_scenes_dataset_log_token')
        batch_op.drop_index(batch_op.f('ix_scenes_dataset_id'))

    op.drop_table('scenes')
    with op.batch_alter_table('instances', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_instances_dataset_id'))
        batch_op.drop_index(batch_op.f('ix_instances_category_token'))

    op.drop_table('instances')
    with op.batch_alter_table('calibrated_sensors', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_calibrated_sensors_sensor_token'))
        batch_op.drop_index(batch_op.f('ix_calibrated_sensors_dataset_id'))

    op.drop_table('calibrated_sensors')
    with op.batch_alter_table('visibilities', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_visibilities_dataset_id'))

    op.drop_table('visibilities')
    with op.batch_alter_table('sensors', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sensors_dataset_id'))
        batch_op.drop_index('ix_sensors_dataset_channel')

    op.drop_table('sensors')
    with op.batch_alter_table('map_meta', schema=None) as batch_op:
        batch_op.drop_index('ix_map_meta_dataset_location')
        batch_op.drop_index(batch_op.f('ix_map_meta_dataset_id'))

    op.drop_table('map_meta')
    with op.batch_alter_table('logs', schema=None) as batch_op:
        batch_op.drop_index('ix_logs_dataset_location')
        batch_op.drop_index(batch_op.f('ix_logs_dataset_id'))

    op.drop_table('logs')
    with op.batch_alter_table('ego_poses', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ego_poses_dataset_id'))

    op.drop_table('ego_poses')
    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.drop_index('ix_categories_dataset_name')
        batch_op.drop_index(batch_op.f('ix_categories_dataset_id'))

    op.drop_table('categories')
    with op.batch_alter_table('attributes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_attributes_dataset_id'))

    op.drop_table('attributes')
    op.drop_table('datasets')
    # ### end Alembic commands ###
