"""add run status and scene_started index

Revision ID: 30b25f55e4c7
Revises: 2137e2545219
Create Date: 2026-09-02 11:58:58.144444+00:00

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '30b25f55e4c7'
down_revision: str | None = '2137e2545219'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('depth_estimation_params', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(), server_default=sa.text("'running'"), nullable=False))
        batch_op.create_index('ix_depth_estimation_params_scene_started', ['scene_token', 'started_at'], unique=False)
        batch_op.create_index('ix_depth_estimation_params_scene_status_started', ['scene_token', 'status', 'started_at'], unique=False)

    with op.batch_alter_table('detection_2d_params', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(), server_default=sa.text("'running'"), nullable=False))
        batch_op.create_index('ix_detection_2d_params_scene_started', ['scene_token', 'started_at'], unique=False)
        batch_op.create_index('ix_detection_2d_params_scene_status_started', ['scene_token', 'status', 'started_at'], unique=False)

    with op.batch_alter_table('instance_tracking_2d_params', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(), server_default=sa.text("'running'"), nullable=False))
        batch_op.create_index('ix_instance_tracking_2d_params_scene_started', ['scene_token', 'started_at'], unique=False)
        batch_op.create_index('ix_instance_tracking_2d_params_scene_status_started', ['scene_token', 'status', 'started_at'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('instance_tracking_2d_params', schema=None) as batch_op:
        batch_op.drop_index('ix_instance_tracking_2d_params_scene_status_started')
        batch_op.drop_index('ix_instance_tracking_2d_params_scene_started')
        batch_op.drop_column('status')

    with op.batch_alter_table('detection_2d_params', schema=None) as batch_op:
        batch_op.drop_index('ix_detection_2d_params_scene_status_started')
        batch_op.drop_index('ix_detection_2d_params_scene_started')
        batch_op.drop_column('status')

    with op.batch_alter_table('depth_estimation_params', schema=None) as batch_op:
        batch_op.drop_index('ix_depth_estimation_params_scene_status_started')
        batch_op.drop_index('ix_depth_estimation_params_scene_started')
        batch_op.drop_column('status')

    # ### end Alembic commands ###
