"""add global track id

Revision ID: 3bf0661eeb75
Revises: 08cad7c7ff00
Create Date: 2026-09-17 04:38:12.232440+00:00

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3bf0661eeb75'
down_revision: str | None = '08cad7c7ff00'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('box_fittings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('global_track_id', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('is_primary', sa.Boolean(), server_default=sa.text('1'), nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('box_fittings', schema=None) as batch_op:
        batch_op.drop_column('is_primary')
        batch_op.drop_column('global_track_id')

    # ### end Alembic commands ###
