"""add box fitting tables

Revision ID: 1bb81b70e991
Revises: 9c04f1f1f330
Create Date: 2026-09-06 20:05:07.826838+00:00

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = '1bb81b70e991'
down_revision: str | None = '9c04f1f1f330'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lidar_pointclouds',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('dataset_id', sa.String(), nullable=False),
    sa.Column('sample_token', sa.String(), nullable=False),
    sa.Column('sample_data_token', sa.String(), nullable=False),
    sa.Column('depth_estimation_params_id', sa.String(), nullable=False),
    sa.Column('pointcloud_path', sa.String(), nullable=False),
    sa.Column('coordinate_frame', sa.String(), server_default=sa.text("'ego'"), nullable=False),
    sa.Column('num_sweeps', sa.Integer(), server_default=sa.text('1'), nullable=False),
    sa.Column('num_points', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('num_ground_points', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['dataset_id'], ['datasets.id'], name=op.f('fk_lidar_pointclouds_dataset_id_datasets'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['depth_estimation_params_id'], ['depth_estimation_params.id'], name=op.f('fk_lidar_pointclouds_depth_estimation_params_id_depth_estimation_params'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sample_data_token'], ['sample_data.token'], name=op.f('fk_lidar_pointclouds_sample_data_token_sample_data'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sample_token'], ['samples.token'], name=op.f('fk_lidar_pointclouds_sample_token_samples'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_lidar_pointclouds'))
    )
    with op.batch_alter_table('lidar_pointclouds', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_lidar_pointclouds_dataset_id'), ['dataset_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_lidar_pointclouds_depth_estimation_params_id'), ['depth_estimation_params_id'], unique=False)
        batch_op.create_index('ix_lidar_pointclouds_params_sample', ['depth_estimation_params_id', 'sample_token'], unique=False)
        batch_op.create_index(batch_op.f('ix_lidar_pointclouds_sample_data_token'), ['sample_data_token'], unique=False)
        batch_op.create_index(batch_op.f('ix_lidar_pointclouds_sample_token'), ['sample_token'], unique=False)

    op.create_table('box_fittings',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('dataset_id', sa.String(), nullable=False),
    sa.Column('depth_estimation_params_id', sa.String(), nullable=False),
    sa.Column('instance_tracking_2d_id', sa.String(), nullable=False),
    sa.Column('sample_data_token', sa.String(), nullable=False),
    sa.Column('sample_annotation_token', sa.String(), nullable=True),
    sa.Column('track_id', sa.String(), nullable=False),
    sa.Column('label', sa.String(), nullable=False),
    sa.Column('mask_rle_closed', sa.JSON(), nullable=True),
    sa.Column('points_depth_ego', sa.JSON(), nullable=True),
    sa.Column('points_lidar_ego', sa.JSON(), nullable=True),
    sa.Column('num_points_depth', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('num_points_lidar', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('depth_align_scale', sa.Float(), nullable=True),
    sa.Column('depth_align_shift', sa.Float(), nullable=True),
    sa.Column('center_ego', sa.JSON(), nullable=True),
    sa.Column('size_wlh', sa.JSON(), nullable=True),
    sa.Column('yaw_ego', sa.Float(), nullable=True),
    sa.Column('fitting_score', sa.Float(), nullable=True),
    sa.Column('status', sa.String(), server_default=sa.text("'fitted'"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('manually_modified', sa.Boolean(), server_default=sa.text('0'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['dataset_id'], ['datasets.id'], name=op.f('fk_box_fittings_dataset_id_datasets'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['depth_estimation_params_id'], ['depth_estimation_params.id'], name=op.f('fk_box_fittings_depth_estimation_params_id_depth_estimation_params'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['instance_tracking_2d_id'], ['instance_tracking_2ds.id'], name=op.f('fk_box_fittings_instance_tracking_2d_id_instance_tracking_2ds'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sample_annotation_token'], ['sample_annotations.token'], name=op.f('fk_box_fittings_sample_annotation_token_sample_annotations'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['sample_data_token'], ['sample_data.token'], name=op.f('fk_box_fittings_sample_data_token_sample_data'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_box_fittings'))
    )
    with op.batch_alter_table('box_fittings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_box_fittings_dataset_id'), ['dataset_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_box_fittings_depth_estimation_params_id'), ['depth_estimation_params_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_box_fittings_instance_tracking_2d_id'), ['instance_tracking_2d_id'], unique=False)
        batch_op.create_index('ix_box_fittings_params_sample_data', ['depth_estimation_params_id', 'sample_data_token'], unique=False)
        batch_op.create_index('ix_box_fittings_params_track', ['depth_estimation_params_id', 'track_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_box_fittings_sample_annotation_token'), ['sample_annotation_token'], unique=False)
        batch_op.create_index(batch_op.f('ix_box_fittings_sample_data_token'), ['sample_data_token'], unique=False)

    with op.batch_alter_table('depth_estimation_params', schema=None) as batch_op:
        batch_op.add_column(sa.Column('use_lidar', sa.Boolean(), server_default=sa.text('0'), nullable=False))
        batch_op.add_column(sa.Column('num_lidar_sweeps', sa.Integer(), server_default=sa.text('1'), nullable=False))
        batch_op.add_column(sa.Column('mask_params', sa.JSON(), server_default=sa.text("'{}'"), nullable=False))
        batch_op.add_column(sa.Column('depth_params', sa.JSON(), server_default=sa.text("'{}'"), nullable=False))
        batch_op.add_column(sa.Column('lidar_params', sa.JSON(), server_default=sa.text("'{}'"), nullable=False))
        batch_op.add_column(sa.Column('box_fitting_params', sa.JSON(), server_default=sa.text("'{}'"), nullable=False))
        batch_op.alter_column('sample_interval',
               existing_type=sa.INTEGER(),
               server_default=sa.text('1'),
               existing_nullable=False)
        batch_op.drop_column('extra_options')
        batch_op.drop_column('max_depth')
        batch_op.drop_column('min_points_per_box')
        batch_op.drop_column('depth_alignment_method')
        batch_op.drop_column('box_fitting_method')
        batch_op.drop_column('point_fusion_mode')
        batch_op.drop_column('outlier_percentile')

    with op.batch_alter_table('depth_estimations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('depth_width', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('depth_height', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('depth_estimations', schema=None) as batch_op:
        batch_op.drop_column('depth_height')
        batch_op.drop_column('depth_width')

    with op.batch_alter_table('depth_estimation_params', schema=None) as batch_op:
        batch_op.add_column(sa.Column('outlier_percentile', sa.FLOAT(), nullable=False))
        batch_op.add_column(sa.Column('point_fusion_mode', sa.VARCHAR(), nullable=False))
        batch_op.add_column(sa.Column('box_fitting_method', sa.VARCHAR(), nullable=False))
        batch_op.add_column(sa.Column('depth_alignment_method', sa.VARCHAR(), nullable=False))
        batch_op.add_column(sa.Column('min_points_per_box', sa.INTEGER(), nullable=False))
        batch_op.add_column(sa.Column('max_depth', sa.FLOAT(), nullable=False))
        batch_op.add_column(sa.Column('extra_options', sqlite.JSON(), nullable=True))
        batch_op.alter_column('sample_interval',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
        batch_op.drop_column('box_fitting_params')
        batch_op.drop_column('lidar_params')
        batch_op.drop_column('depth_params')
        batch_op.drop_column('mask_params')
        batch_op.drop_column('num_lidar_sweeps')
        batch_op.drop_column('use_lidar')

    with op.batch_alter_table('box_fittings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_box_fittings_sample_data_token'))
        batch_op.drop_index(batch_op.f('ix_box_fittings_sample_annotation_token'))
        batch_op.drop_index('ix_box_fittings_params_track')
        batch_op.drop_index('ix_box_fittings_params_sample_data')
        batch_op.drop_index(batch_op.f('ix_box_fittings_instance_tracking_2d_id'))
        batch_op.drop_index(batch_op.f('ix_box_fittings_depth_estimation_params_id'))
        batch_op.drop_index(batch_op.f('ix_box_fittings_dataset_id'))

    op.drop_table('box_fittings')
    with op.batch_alter_table('lidar_pointclouds', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_lidar_pointclouds_sample_token'))
        batch_op.drop_index(batch_op.f('ix_lidar_pointclouds_sample_data_token'))
        batch_op.drop_index('ix_lidar_pointclouds_params_sample')
        batch_op.drop_index(batch_op.f('ix_lidar_pointclouds_depth_estimation_params_id'))
        batch_op.drop_index(batch_op.f('ix_lidar_pointclouds_dataset_id'))

    op.drop_table('lidar_pointclouds')
    # ### end Alembic commands ###
