"""add hull xy

Revision ID: fff5f8018c94
Revises: 2b391f352b28
Create Date: 2026-09-09 10:32:33.228456+00:00

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fff5f8018c94'
down_revision: str | None = '2b391f352b28'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('box_fittings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('hull_xy', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('box_fittings', schema=None) as batch_op:
        batch_op.drop_column('hull_xy')

    # ### end Alembic commands ###
