"""add track id inheritance

Revision ID: efd32e1637bb
Revises: 3ac7334dc50b
Create Date: 2026-09-14 11:38:52.610022+00:00

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'efd32e1637bb'
down_revision: str | None = '3ac7334dc50b'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('instance_tracking_2d_params', schema=None) as batch_op:
        batch_op.add_column(sa.Column('track_id_inheritance', sa.String(), server_default=sa.text("'continuous_id'"), nullable=False))

    with op.batch_alter_table('instance_tracking_2ds', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_selected', sa.Boolean(), server_default=sa.text('1'), nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('instance_tracking_2ds', schema=None) as batch_op:
        batch_op.drop_column('is_selected')

    with op.batch_alter_table('instance_tracking_2d_params', schema=None) as batch_op:
        batch_op.drop_column('track_id_inheritance')

    # ### end Alembic commands ###
