"""add depth correction

Revision ID: 3e72669dffbc
Revises: 7af106f4f793
Create Date: 2026-09-22 08:58:32.993562+00:00

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3e72669dffbc'
down_revision: str | None = '7af106f4f793'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('box_fittings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('points_depth_corrected_ego', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('depth_correction', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('box_fittings', schema=None) as batch_op:
        batch_op.drop_column('depth_correction')
        batch_op.drop_column('points_depth_corrected_ego')

    # ### end Alembic commands ###
