"""add reclassified as

Revision ID: 7af106f4f793
Revises: 3bf0661eeb75
Create Date: 2026-09-17 13:43:06.236029+00:00

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7af106f4f793'
down_revision: str | None = '3bf0661eeb75'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('detection_2ds', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reclassified_as', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('detection_2ds', schema=None) as batch_op:
        batch_op.drop_column('reclassified_as')

    # ### end Alembic commands ###
