"""add detection reclassification

Revision ID: 08cad7c7ff00
Revises: efd32e1637bb
Create Date: 2026-09-15 19:33:19.568481+00:00

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '08cad7c7ff00'
down_revision: str | None = 'efd32e1637bb'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('detection_2ds', schema=None) as batch_op:
        batch_op.add_column(sa.Column('detection_label', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('0'), nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('detection_2ds', schema=None) as batch_op:
        batch_op.drop_column('is_deleted')
        batch_op.drop_column('detection_label')

    # ### end Alembic commands ###
