"""add tracking sweep and iou params

Revision ID: 6638b0e66587
Revises: 30b25f55e4c7
Create Date: 2026-09-02 14:51:38.392586+00:00

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6638b0e66587'
down_revision: str | None = '30b25f55e4c7'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('instance_tracking_2d_params', schema=None) as batch_op:
        batch_op.add_column(sa.Column('num_sweeps', sa.Integer(), server_default=sa.text('1'), nullable=False))
        batch_op.add_column(sa.Column('iou_method', sa.String(), server_default=sa.text("'box'"), nullable=False))
        batch_op.add_column(sa.Column('iou_label_match', sa.String(), server_default=sa.text("'label'"), nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('instance_tracking_2d_params', schema=None) as batch_op:
        batch_op.drop_column('iou_label_match')
        batch_op.drop_column('iou_method')
        batch_op.drop_column('num_sweeps')

    # ### end Alembic commands ###
