"""drop raw instance points

Revision ID: 2b391f352b28
Revises: 159ffc9db439
Create Date: 2026-09-08 16:08:09.949961+00:00

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = '2b391f352b28'
down_revision: str | None = '159ffc9db439'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('box_fittings', schema=None) as batch_op:
        batch_op.drop_column('points_lidar_raw_ego')
        batch_op.drop_column('points_depth_raw_ego')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('box_fittings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('points_depth_raw_ego', sqlite.JSON(), nullable=True))
        batch_op.add_column(sa.Column('points_lidar_raw_ego', sqlite.JSON(), nullable=True))

    # ### end Alembic commands ###
