"""add instance origin

Revision ID: 9c04f1f1f330
Revises: 6638b0e66587
Create Date: 2026-09-03 16:07:30.262894+00:00

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9c04f1f1f330'
down_revision: str | None = '6638b0e66587'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('instance_tracking_2ds', schema=None) as batch_op:
        batch_op.add_column(sa.Column('origin', sa.String(), server_default=sa.text("'prompt'"), nullable=False))
        batch_op.create_index('ix_instance_tracking_2ds_params_origin', ['instance_tracking_2d_params_id', 'sample_data_token', 'origin'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('instance_tracking_2ds', schema=None) as batch_op:
        batch_op.drop_index('ix_instance_tracking_2ds_params_origin')
        batch_op.drop_column('origin')

    # ### end Alembic commands ###
