"""add detection sublabel

Revision ID: 3ac7334dc50b
Revises: bde210251f3d
Create Date: 2026-09-13 12:33:51.621597+00:00

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3ac7334dc50b'
down_revision: str | None = 'bde210251f3d'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('detection_2ds', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sublabel', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('detection_2ds', schema=None) as batch_op:
        batch_op.drop_column('sublabel')

    # ### end Alembic commands ###
