"""add fit metrics

Revision ID: bde210251f3d
Revises: fff5f8018c94
Create Date: 2026-09-09 10:38:46.098920+00:00

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bde210251f3d'
down_revision: str | None = 'fff5f8018c94'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('box_fittings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fit_metrics', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('box_fittings', schema=None) as batch_op:
        batch_op.drop_column('fit_metrics')

    # ### end Alembic commands ###
