# syntax=docker/dockerfile:1
# Base image
FROM jidohub/base-cu124-devel-ubuntu22.04:latest

# SigLIP2 Python API needs http proxy to download weights from Huggin Face
ARG HTTP_PROXY
ARG HTTPS_PROXY
ENV HTTP_PROXY=${HTTP_PROXY}
ENV HTTPS_PROXY=${HTTPS_PROXY}
# Install transformers
RUN pip install transformers

WORKDIR /workspace

############################
# Create non-root user
############################
ARG USERNAME=developer
ARG UID=1000
ARG GID=1000
RUN groupadd -g ${GID} ${USERNAME} \
    && useradd -m -u ${UID} -g ${GID} -s /bin/bash ${USERNAME} \
    && chown -R ${UID}:${GID} /workspace
USER ${USERNAME}
